# Local development
version: '3.8'
services:

  s57server:
    image: 'ghcr.io/manimaul/njord-chart-server:latest'
    networks:
      - overlay
    ports:
      - "9000:9000"
    environment:
      JAVA_OPTS: "-Dcharts.chartTempData=/tmp/njord/data -Dcharts.pgHost=postgres -Dcharts.webStaticContent=/opt/chart_server/public"

    depends_on:
      - postgres

  postgres:
    image: 'postgis/postgis:13-3.1'
    networks:
      - overlay
    ports:
      - "5432:5432"
      # We only expose the port here for local dev purposes
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: s57server

  postgressetup:
    build:
      context: ./chart_server_db/postgres_init
      dockerfile: Dockerfile
    depends_on:
      - postgres
    networks:
      - overlay
    restart: "no"
    volumes:
      - ./chart_server_db/postgres_init/scripts:/postgres_init
    environment:
      PGUSER: admin
      PGPASSWORD: mysecretpassword
      PGHOST: postgres
      PGPORT: 5432
      PGDATABASE: s57server

    entrypoint: [ "/postgres_init/postgres_init.sh" ]


networks:
  overlay:
