apiVersion: v1
kind: Namespace
metadata:
  name: njord
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: njord-chart-scaler
spec:
  scaleTargetRef:
    kind: ReplicaSet
    name: njord-chart-dep
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 70
---
apiVersion: v1
kind: Service
metadata:
  name: njord-chart-svc
  namespace: njord
spec:
  ports:
    - name: http
      port: 9000
      targetPort: 9000
  selector:
    app: njord-chart-svc
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: njord-chart-dep
  namespace: njord
spec:
  selector:
    matchLabels:
      app: njord-chart-svc
  template:
    metadata:
      labels:
        app: njord-chart-svc
    spec:
      containers:
        - image: ghcr.io/manimaul/njord-chart-server:latest
          imagePullPolicy: Always
          name: njord-chart-svc
          ports:
            - containerPort: 9000
              name: http
          resources:
            requests:
              cpu: 100m
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    haproxy.org/request-set-header: "l5d-dst-override njord-chart-svc.mxmariner.svc.cluster.local:80"
    haproxy.org/ssl-redirect: "true" # https://www.haproxy.com/documentation/kubernetes/latest/configuration/ingress/
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  name: njord-mxmarineringress
  namespace: njord
spec:
  rules:
    - host: s57dev.mxmariner.com
      http:
        paths:
          - path: /
            backend:
              serviceName: njord-chart-svc
              servicePort: 9000
  tls:
    - hosts:
        - s57dev.mxmariner.com
      secretName: njord-mxmariner-cert
---
# kubectl -n njord create configmap njord-config --from-file=/Users/williamkamp/source/madrona/njord/chart_server/src/main/resources/application.conf
apiVersion: v1
kind: ConfigMap
metadata:
  name: njord-config
  namespace: njord
data:
  application.conf: |
    charts {
        pgUser=admin
        pgPassword=mysecretpassword
        pgHost=njord-postgis-svc.njord.svc.cluster.local
        pgPort=5432
        pgDatabase=s57server

        host = "0.0.0.0"
        port = 9000

        externalScheme = "https"
        externalHostName = "s57dev.mxmariner.com"
        externalPort = 443

        chartMinZoom = 0
        chartMaxZoom = 30

        chartTempData = /tmp/njord/data
    }
---
